// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";

import { sleep } from 'k6';
import http from 'k6/http';


export let options = { 
	vus: 3,
	duration: '30s',
	maxRedirects: 4,
	thresholds: { 
    http_req_failed: ['rate<0.01'],       // < 1% errors
    http_req_duration: [
      'p(90)<350',                        
      'p(95)<450',                        
    ],
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "https://dummyjson.com",
    validID: "2",
    searchName: "Emily"
  }
});

export default function() {
  postman[Request]({
    name: "Get /carts (list)",
    id: "981086fc-87fd-4c78-a389-61f5129a30d3",
    method: "GET",
    address: "{{baseUrl}}/carts",
    //data: '{\r\n  "username": "UpdatedUser"\r\n}',
    post(response) {
      pm.test("200 Status Code", function() {
        pm.response.to.have.status(200);
      });

      pm.test("content-type = application/json", function() {
        const ct = pm.response.headers.get("Content-Type");
        pm.expect(ct).to.include("application/json");
      });

      const json = pm.response.json();
	  const cartsResponseArray = json.carts;

	  pm.test("carts property exists", function () {
      pm.expect(cartsResponseArray).to.not.be.undefined;
	  });

	  if (Array.isArray(cartsResponseArray)) {
	  pm.test("carts array length > 0", function () {
      pm.expect(cartsResponseArray.length).to.be.above(0);
     });
    }

      pm.test("response is json obj", function() {
        pm.expect(pm.response.json()).to.be.an("object");
      });

      pm.test("All carts have required keys", function() {
        cartsResponseArray.slice(0, 6).forEach((v, k) => {
          pm.expect(cartsResponseArray[k]).to.include.keys(
            "id",
            "products",
            "total",
            "userId"
          );
        });
      });
    }
  });
	  sleep(3);

  postman[Request]({
    name: "Get /products /id (single product)",
    id: "222c77a8-4670-4b19-8f04-b1efdb7c79ec",
    method: "GET",
    address: "{{baseUrl}}/products/{{validID}}",
    post(response) {
      const resp = pm.response.json();

      pm.test("200 Status Code", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Content-Type = application/json", function() {
        const ct = pm.response.headers.get("Content-Type");
        pm.expect(ct).to.include("application/json");
      });

      pm.test("Response is json object", function() {
        pm.expect(resp).to.be.an("object");
      });

      pm.test("Valid required keys", function() {
        pm.expect(resp).to.include.keys("id", "title", "price");
      });

      pm.test("Valid key Types", function() {
        pm.expect(resp.id).to.be.an("number");
        pm.expect(resp.title).to.be.an("string");
        pm.expect(resp.price).to.be.an("number");
      });

      const ExpectedID = parseInt(pm.collectionVariables.get("validID"));
      pm.test("ReturnedID = RequestedID", function() {
        pm.expect(resp.id).to.be.equal(ExpectedID);
      });
    }
  });
  sleep(3);

  postman[Request]({
    name: "Get /users/ search",
    id: "9e0a0aeb-632e-46d3-a4fb-7d81b7520029",
    method: "GET",
    address: "{{baseUrl}}/users/search?q={{searchName}}",
    post(response) {
      pm.test("200 Status Code", function() {
        pm.response.to.have.status(200);
      });

      const resp = pm.response.json();
      pm.test("Returned Response is an Object", function() {
        pm.expect(resp).to.be.an("object");
      });

	  pm.test("Users array exists", function () {
	  pm.expect(resp.users).to.not.be.undefined;
	 });

	  if (Array.isArray(resp.users)) {
      pm.test("Returned Response is Not Empty", function () {
      pm.expect(resp.users.length).to.be.above(0);
     });
     }

      const users = resp.users;
      const searchWord = pm.collectionVariables.get("searchName");
      pm.test("First Name has the Searched Word", function() {
        users.forEach((v, k) => {
          pm.expect(v.firstName).to.include(searchWord);
        });
      });
    }
  });
  sleep(3);
}
