// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";

import { sleep } from 'k6';
import http from 'k6/http';

export let options = { 
	vus:20,
	duration:'30s',
	maxRedirects: 4,
	thresholds: {
    http_req_failed: ['rate<0.1'],       // < 1% errors
    http_req_duration: [
      'p(90)<450',                        // 90% < 450ms
      'p(95)<600',                        // 95% < 600ms
    ],
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "https://dummyjson.com",
    validID: "2",
    searchName: "Emily"
  }
});

export default function() {
  postman[Request]({
    name: "Get /carts (list)",
    id: "981086fc-87fd-4c78-a389-61f5129a30d3",
    method: "GET",
    address: "{{baseUrl}}/carts",
    //data: '{\r\n  "username": "UpdatedUser"\r\n}',
    post(response) {
		let json;
		try {
			json = pm.response.json();
		} catch (e) {
			pm.test("Response is valid JSON", () => false);
				return; // stop to avoid failure
			}

		pm.test("200 Status Code", function () {
			pm.expect(pm.response.code).to.eql(200);
		});

		pm.test("Content-Type = application/json", function () {
			const ct = pm.response.headers.get("Content-Type") || "";
			pm.expect(ct).to.include("application/json");
		});

		pm.test("Response is an object", function () {
			pm.expect(json).to.be.an("object");
		});

		const carts = Array.isArray(json.carts) ? json.carts : [];

		pm.test("carts property exists and is an array", function () {
			pm.expect(Array.isArray(carts)).to.eql(true);
		});

		pm.test("carts array may be empty under load (allowed)", function () {
			pm.expect(carts.length).to.be.at.least(0);
		});

		// Only validate keys IF cart exist
		if (carts.length > 0) {
			pm.test("All carts have required keys", function () {
			carts.slice(0, 5).forEach(cart => {
			pm.expect(cart).to.include.keys(
				"id",
				"products",
				"total",
				"userId"
			);
		});
	});
	}
	sleep(1);
	}
	
  });

  sleep(1);
	
  postman[Request]({
    name: "Get /products /id (single product)",
    id: "222c77a8-4670-4b19-8f04-b1efdb7c79ec",
    method: "GET",
    address: "{{baseUrl}}/products/{{validID}}",
    post(response) {
      const resp = pm.response.json();

      pm.test("200 Status Code", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Content-Type = application/json", function() {
        const ct = pm.response.headers.get("Content-Type");
        pm.expect(ct).to.include("application/json");
      });

      pm.test("Response is json object", function() {
        pm.expect(resp).to.be.an("object");
      });

      pm.test("Valid required keys", function() {
        pm.expect(resp).to.include.keys("id", "title", "price");
      });

      pm.test("Valid key Types", function() {
        pm.expect(resp.id).to.be.an("number");
        pm.expect(resp.title).to.be.an("string");
        pm.expect(resp.price).to.be.an("number");
      });

      const ExpectedID = parseInt(pm.collectionVariables.get("validID"));
      pm.test("ReturnedID = RequestedID", function() {
        pm.expect(resp.id).to.be.equal(ExpectedID);
      });
    sleep(1);
	}
  });
	
	sleep(1);
	
  postman[Request]({
    name: "Get /users/ search",
    id: "9e0a0aeb-632e-46d3-a4fb-7d81b7520029",
    method: "GET",
    address: "{{baseUrl}}/users/search?q={{searchName}}",
    post(response) {
      pm.test("200 Status Code", function() {
        pm.response.to.have.status(200);
      });

      const resp = pm.response.json();
      pm.test("Returned Response is an Object", function() {
        pm.expect(resp).to.be.an("object");
      });

      pm.test("Retuned Response is Not Empty", function () {
		const users = pm.response.json().users;
		pm.expect(Array.isArray(users)).to.eql(true);
		pm.expect(users.length).to.be.above(0);
	});

      const users = resp.users || [];
      const searchWord = pm.collectionVariables.get("searchName");
      pm.test("First Name has the Searched Word", function() {
        users.forEach((v, k) => {
          pm.expect(v.firstName).to.include(searchWord);
        });
      });
    sleep(1);
	}
  });
  sleep(1);
}
