name: My project deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: |
          git fetch origin main
          git reset --hard origin/main
      - name: Newman Test
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: newman run Postman-Files/DummyJson.json -e  Postman-Files/Environment.json -d  Postman-Files/UsersData.csv
  
      - name: K6 Smoke Test
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: k6 run Final_K6/SmokeTest.js

      - name: K6 Load Test
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: k6 run Final_K6/LoadTest.js
        
      - name: CPU status
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: w

      - name: Ram status
        working-directory: /home/halahanaqtah/FinalProject-HTU

        run: free -h



