name: My project deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: |
          git fetch origin main
          git reset --hard origin/main
      - name: K6 Run Smoke Test
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run:  ls -la
              k6 run SmokeTest.js
        
      - name: CPU status
        working-directory: /home/halahanaqtah/FinalProject-HTU
        run: w

      - name: Ram status
        working-directory: /home/halahanaqtah/FinalProject-HTU

        run: free -h



